# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9a25c07d403592c881dd305cecaa03466fa7eb5e2d5c415ba2dab52faa749f1b52e0c1b5652c92b1a74322841879973735dbf6c94c995127f61f67f64a99037

test:
  secret_key_base: 337001130e74bbe7001ef44c72ca7484ac79291084dad86cd4dc447c68f08438b279f72ea9c27ab390f6f6cb6d582fb3f7bfe8d20b9205dd5ec748aba8c16260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
